export enum eEspecialidad {
    SALUD_MENTAL = 'SALUD_MENTAL',
    FISIO_KINESIOLOGIA = 'FISIO_KINESIOLOGIA',
    LABORATORIO = 'LABORATORIO',
    ODONTOLOGIA = 'ODONTOLOGIA',
    MEDICINA_GENERAL = 'MEDICINA_GENERAL',
    PEDIATRIA = 'PEDIATRIA'
  }