export enum eEspecialidad {
    //CONSULTORIOS EXTERNOS
    SALUD_MENTAL = "SALUD_MENTAL",
    FISIO_KINESIOLOGIA = "FISIO_KINESIOLOGIA",
    ODONTOLOGIA = "ODONTOLOGIA",
    MEDICINA_GENERAL = "MEDICINA_GENERAL",
    PEDIATRIA = "PEDIATRIA",

    //ESTUDIOS CLINICOS
    //RAYOS = 'RAYOS',
    LABORATORIO = "LABORATORIO",//SIN HORARIOS
    //DERIVADO_GUARDIA = 'DERIVADO_GUARDIA'//SIN HORARIOS
}